/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'CMSISrtxSemaphore' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* ARM::CMSIS:RTOS:Keil RTX@4.82.0 */
#define RTE_CMSIS_RTOS                  /* CMSIS-RTOS */
#define RTE_CMSIS_RTOS_RTX              /* CMSIS-RTOS Keil RTX */


#endif /* RTE_COMPONENTS_H */
